# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09c465c40ef354aec0899d6d508158472028fd08fd8ac1203b2368686107920956af6285dc02601e7cb0a13223a0a76792f08035f443e6072717523f748e2f79

test:
  secret_key_base: 024bd5c2a701dfc0e8f23ce03fcb227c335ad217bb3d71de0e83f5bf6fd3c43cad6e6d97a2d1f2a0fa273f7a5d887be01162d4939756062ccc8a82870a338844

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
